version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=su123
      - POSTGRES_DB=postgres
    container_name: parcial
    volumes:
      - ./pgdata:/var/lib/postgresql/data
